name: Terraform_Pipeling
  
# on: workflow_dispatch

on: 
  push:
    branches:
     - ' main/**'
     - 'master/**'

jobs:
  Terraform_init:
    name: Terraform Init, plan
    runs-on : self-hosted
    steps:
       - name: Checkout
         uses: actions/checkout@v5.0.0
      

       - name: Install Terraform
  # You may pin to the exact commit or the version.
  # uses: little-core-labs/install-terraform@1e577535d279f1999a5abf60337ddc3ff225e79d
         uses: little-core-labs/install-terraform@v2.0.0
         with:
            # Version of terraform to download
            version: 1.13.0


# after rubnning install, next will be terraform init. if you have backenf configured here, then before this step, its important to do azure login.
# so itcan access the storage account container.

       - name: Azure Login
          uses: Azure/login@v2.3.0
          with:
            # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
            creds: # optional
            # ClientId of the Azure Service principal created.
            client-id: # optional
            # TenantId of the Azure Service principal created.
            tenant-id: # optional
            # Azure subscriptionId
            subscription-id: # optional
            # Set this value to true to enable Azure PowerShell Login in addition to Azure CLI login
            enable-AzPSSession: # optional
            # Name of the environment. Supported values are azurecloud, azurestack, azureusgovernment, azurechinacloud, azuregermancloud. Default being azurecloud
            environment: # optional, default is azurecloud
            # Set this value to true to enable support for accessing tenants without subscriptions
            allow-no-subscriptions: # optional
            # Provide audience field for access-token. Default value is api://AzureADTokenExchange
            audience: # optional, default is api://AzureADTokenExchange
            # The type of authentication. Supported values are SERVICE_PRINCIPAL, IDENTITY. Default value is SERVICE_PRINCIPAL
            auth-type: # optional, default is SERVICE_PRINCIPAL
                  
